### ISSUE TITLE
Can not create new table after renaming a motif

### ISSUE THREAD

**Issue by mgledi** [mgledi/DiffLogoUI#16]
Reproduce:
1. upload three motifs
2. generate diffLogo
3. rename motif
4. it is not possible to regenerate the diffLogoTable.

**Comment by JayGray** [comment]
Can you add som additional information.
I tried to reproduce with `Mad`, `Max` and `Myn` examples,
following your advice and it worked for me.

**Comment by mgledi** [comment]
Don't know what you have done. But it is truely working.
